language: python

python:
  - "2.7"
  - "3.4"

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - libatlas-base-dev
    - gfortran

install:
  - cd $TRAVIS_BUILD_DIR
  - pip install --upgrade pip
  - pip install --upgrade pytest pytest-cov
  - pip install codecov unipath requests scikit-learn
  - python setup.py install

script:
  - py.test --cov=./

cache:
  - apt
  - pip
  - directories:
    - $HOME/.cache/pip

after_success:
  - codecov
