language: python

python:
  - "2.7"
  - "3.4"

before_install:
  - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran

install: 
  - pip install unipath requests 
  - python setup.py install

script: py.test --ignore=revrand/optimize/nlopt_wrap.py