language: python

python:
  - "2.7"
  - "3.4"

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - libatlas-base-dev
    - gfortran

before_install:
  - wget http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz
  - tar -xvf nlopt-2.4.2.tar.gz
  - cd nlopt-2.4.2

install:
  - PYTHON=$(which python) ./configure --prefix=$(dirname $(dirname $(which python))) --enable-shared
  - make
  - make install
  - pip install --upgrade pip
  - pip install scipy
  - python setup.py install

script: py.test
