language: python

python:
  - "2.7"
  - "3.4"

# command to install dependencies
virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran

install: python setup.py install

# command to run tests
script: py.test --ignore=revrand/optimize/nlopt_wrap.py