language: python

sudo: required
dist: trusty

python:
  - "3.4"

virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
    - libnlopt0
    - python-nlopt

script: python -c 'import nlopt'

