sudo: required

language: python

services:
  - docker

python:
  - "2.7"
  - "3.6"

before_install:
  - docker build -t nicta/revrand .
  - docker ps -a

script:
  - docker run -w /usr/src/python/revrand nicta/revrand py.test --cov=./

after_success:
  - docker run -w /usr/src/python/revrand nicta/revrand codecov
