language: python

sudo: false

python:
  - "2.7_with_system_site_packages"
  - "3.4"

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - libatlas-base-dev
    - gfortran

before_install:
  - pip install --upgrade pip
  - pip install unipath requests 

install: 
  - python setup.py install

script: py.test

cache:
  - apt
  - pip
  - directories:
    - $HOME/.cache/pip
