language: python

sudo: false

python:
  - "2.7"
  - "3.4"

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
    - python-nlopt

virtualenv:
  system_site_packages: true

before_install:
  - pip install --upgrade pip
  - pip install unipath requests 

install: 
  - python setup.py install

script: py.test

cache:
  - apt
  - pip
  - directories:
    - $HOME/.cache/pip
