language: python

sudo: false

python:
  - "2.7"
  - "3.4"

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran

before_install:
  - pip install --upgrade pip

install: 
  - pip install unipath requests 
  - python setup.py install

script: py.test --ignore=revrand/optimize/nlopt_wrap.py

cache:
  - apt
  - pip
  - directories:
    - $HOME/.cache/pip
