language: python

addons:
  apt:
    packages:
    - python3-numpy
    - python3-scipy
    - python-numpy
    - python-scipy

python:
  - "2.7"
  - "3.4"

install:
  - cd $TRAVIS_BUILD_DIR
  - pip install pytest pytest-cov
  - pip install codecov unipath requests scikit-learn
  - python setup.py install

script:
  - py.test --cov=./

cache:
  - apt
  - pip
  - directories:
    - $HOME/.cache/pip

after_success:
  - codecov
